# Generated by Django 2.2.10 on 2020-08-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('munID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fid', models.CharField(max_length=100)),
                ('districtID', models.CharField(max_length=100)),
                ('ProvinceName', models.CharField(max_length=100)),
                ('DistrictName', models.CharField(max_length=100)),
                ('PalikaName', models.CharField(max_length=100)),
                ('PalikaType', models.CharField(max_length=100)),
                ('TotalWards', models.CharField(blank=True, max_length=100, null=True)),
                ('HQMunicipalCenter', models.CharField(blank=True, max_length=100)),
                ('NumberingTotalPalikas', models.CharField(max_length=100)),
                ('NoPalikaPerDistrict', models.CharField(max_length=100)),
                ('ContactPersonITOfficer', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactPersonPhNumb', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNumMunicipality', models.CharField(blank=True, max_length=100, null=True)),
                ('Website', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('TotalArea', models.CharField(max_length=100, null=True)),
                ('TotPopulation', models.CharField(max_length=100)),
                ('TotMale', models.CharField(max_length=100)),
                ('TotFemale', models.CharField(max_length=100)),
                ('TotHousehold', models.CharField(max_length=100)),
                ('Xcord', models.CharField(max_length=100)),
                ('Ycord', models.CharField(max_length=100)),
                ('verification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='All_Temp',
            fields=[
                ('munID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fid', models.CharField(max_length=100)),
                ('districtID', models.CharField(max_length=100)),
                ('ProvinceName', models.CharField(max_length=100)),
                ('DistrictName', models.CharField(max_length=100)),
                ('PalikaName', models.CharField(max_length=100)),
                ('PalikaType', models.CharField(max_length=100)),
                ('TotalWards', models.CharField(blank=True, max_length=100, null=True)),
                ('HQMunicipalCenter', models.CharField(blank=True, max_length=100)),
                ('NumberingTotalPalikas', models.CharField(max_length=100)),
                ('NoPalikaPerDistrict', models.CharField(max_length=100)),
                ('ContactPersonITOfficer', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactPersonPhNumb', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNumMunicipality', models.CharField(blank=True, max_length=100, null=True)),
                ('Website', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('TotalArea', models.CharField(max_length=100, null=True)),
                ('TotPopulation', models.CharField(max_length=100)),
                ('TotMale', models.CharField(max_length=100)),
                ('TotFemale', models.CharField(max_length=100)),
                ('TotHousehold', models.CharField(max_length=100)),
                ('Xcord', models.CharField(max_length=100)),
                ('Ycord', models.CharField(max_length=100)),
                ('verification', models.CharField(max_length=100)),
            ],
        ),
    ]
